# trigger:
#   batch: true
#   branches:
#     include:
#     - main
#   paths:
#     exclude: 
#     - README.md
#     - LICENSE
#     - api
#     - website
#     include:
#     - db
#     - pipelines/database/azure-pipelines.yml

variables:
  service_connection_name: "SC-AzureDevOps" 

pool:
  vmImage: ubuntu-latest

stages:
  - stage: main
    jobs:
    - job: CleanUp
      pool:
        vmImage: ubuntu-latest #or ubuntu-20.04
      steps:
      - task: AzureCLI@2
        displayName: 'Delete RGs'
        inputs:
          azureSubscription:  ${{ variables.service_connection_name }}
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |

            az group list --query "[?tags.delete == 'true'].name" -o tsv | xargs --no-run-if-empty -l az group delete --yes --name

            az group list --query "[?tags.delete == 'true'].name" -o table | xargs -otl az group delete --no-wait --yes -n
            az group list --query "[?tags.delete == 'true']" -o tsv | grep rg