parameters:
  - name: myVar
    default: "It's alive!"

variables:
  myVariable: 'ValueFromVar'

stages:
  - stage: dev
    jobs:
    - job: Linux
      pool:
        vmImage: ubuntu-latest #or ubuntu-20.04
      steps:
      - bash: ls -ltr
      - bash: echo "Parameters ${{ parameters.myVar }}"
      - task: Bash@3
        displayName: Display Variable
        inputs:
          targetType: 'inline'
          script: echo 'Variables $(myVariable)'
      - task: PowerShell@2
        displayName: Run ps1 script file
        inputs:
          filePath: './pipelines/demo-pipeline/file.ps1'
      - task: PowerShell@2
        displayName: 'Get-AzResourceGroup'
        inputs:
          azureSubscription: 'AzureDevOps'
          targetType: 'inline'
          script: |
            Get-AzResourceGroup

    - job: Windows
      pool:
        vmImage: windows-latest #or windows-2022
      steps:
      - task: PowerShell@2
        displayName: Display parameter
        inputs:
          targetType: 'inline'
          script: 'Write-Host "parameters: ${{ parameters.myVar }}"'
      - task: PowerShell@2
        displayName: Run ps1 script file
        inputs:
          filePath: './pipelines/demo-pipeline/file.ps1'
      - task: AzureCLI@2
        displayName: Azure CLI
        inputs:
          azureSubscription: 'AzureDevOps'
          scriptType: ps
          scriptLocation: inlineScript
          inlineScript: |
            az --version
            az account show
