parameters:
  - name: myVar
    default: "It's alive!"

variables:
  myVariable: 'ValueFromVar'

stages:
  - stage: dev
    jobs:
    - job: Linux
      pool:
        vmImage: ubuntu-latest #or ubuntu-20.04
      steps:
      - bash: echo "Parameters ${{ parameters.myVar }}"
      - task: Bash@3
        displayName: Display Variable
        inputs:
          targetType: 'inline'
          script: echo 'Variables $(myVariable)'
    - job: Windows
      pool:
        vmImage: windows-latest #or windows-2022
      steps:
      - task: PowerShell@2
        displayName: Display parameter
        inputs:
          targetType: 'inline'
          script: 'Write-Host "parameters: ${{ parameters.myVar }}"' 
