parameters:
  - name: myVar
    default: "It's alive!"

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  myVariable: 'ValueFromVar'

stages:
  - stage: dev
    jobs:
    - job: Linux
      pool:
        vmImage: ubuntu-latest
      steps:
      - bash: echo "Parameters ${{ parameters.myVar }}"
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: echo 'Variables $(myVariable)'
