parameters:
  - name: myVar
    default: "It's alive!"

stages:
  - stage: dev
    jobs:
    - job: Linux
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: echo '$(myVar)'